---
abstract: 'Just some syntax sugar for DBIx::Class'
author:
  - 'Naveed Massjouni <naveed@vt.edu>'
build_requires:
  DBI: 0
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::Modern: 0
  Test::More: 0
  Test::Requires: 0
  base: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBICx-Sugar
requires:
  Carp: 0
  DBIx::Class: 0
  Exporter: 0
  Memoize: 0
  Module::Load: 0
  SQL::Translator: 0.11018
  YAML: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/ironcamel/DBICx-Sugar/issues
  repository: git://github.com/ironcamel/DBICx-Sugar.git
version: 0.0001
